FROM node:18-alpine3.14 AS builder

ARG REACT_APP_SERVER

WORKDIR /app

COPY . .

RUN yarn install --frozen-lockfile
RUN yarn build

FROM nginx:alpine

COPY --from=builder /app/src/dist /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
