FROM node:18-alpine3.14 AS builder

ARG REACT_APP_SERVER

WORKDIR /app

COPY . .

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
RUN yarn build
# COPY package.json ./
# RUN npm install
# RUN npm run build


FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
